title: "VERSA Help Center"
description: "Official Documentation for the VERSA Discord Bot by Afterparty Bot Labs"
show_downloads: false
theme_color: "#00C7CF"
footer_brand: "Afterparty Bot Labs"
footer_link: "https://afterpartylabs.xyz"
logo: "/assets/images/versa-logo.png"
icon: "/assets/images/versa-logo.png"
favicon: "/assets/images/versa-logo.png"
cta_invite_url: "https://discord.com/api/oauth2/authorize?client_id=1200483261533650966&permissions=8&scope=applications.commands+bot"
topgg_url: "https://top.gg/bot/1200483261533650966/vote"
cta_dashboard_url: "https://botversa.xyz/"
cta_support_url: "https://discord.gg/BusuZp2G8w"
cta_docs_url: "https://help.botversa.xyz"
url: "https://botlabs-xyz.github.io"
baseurl: "/versa-docs"
markdown: kramdown